name: root
dependencies:
  - python=2.7
  - notebook=5.0
  - ipywidgets=6.0
  - requests=2.14
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - pandas
    - matplotlib
    - pymongo
    - imgurpython
    - SQLAlchemy
    - PyMySQL
