name: ipython-notebook
dependencies:
  - python=2.7
  - notebook
  - ipywidgets
  - requests
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - twstock
    - pandas
    - matplotlib
    - pymongo
    - imgurpython
    - SQLAlchemy
    - PyMySQL
